name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ master ]        # change to main if needed
    paths:
      - "backend/**"

permissions:
  id-token: write               # required for OIDC
  contents: read

env:
  AWS_REGION: af-south-1
  EB_APP: h2go-api
  EB_ENV: H2go-api-env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::101573021364:role/h2go-eb-github-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Detect lockfile
        id: lock
        run: |
          if [ -f backend/package-lock.json ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "lock=backend/package-lock.json" >> $GITHUB_OUTPUT
          elif [ -f backend/yarn.lock ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "lock=backend/yarn.lock" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "lock=" >> $GITHUB_OUTPUT
          fi

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ steps.lock.outputs.manager }}
          cache-dependency-path: ${{ steps.lock.outputs.lock }}

      - name: Install & Build (backend)
        working-directory: backend
        run: |
          if [ "${{ steps.lock.outputs.manager }}" = "yarn" ]; then
            corepack enable
            yarn install --frozen-lockfile
            yarn build
          else
            npm ci
            npm run build
          fi

      - name: Create deploy bundle
        run: |
          rm -rf deploy && mkdir -p deploy/dist
          cp backend/package.json deploy/
          if [ -f backend/package-lock.json ]; then cp backend/package-lock.json deploy/; fi
          if [ -f backend/yarn.lock ]; then cp backend/yarn.lock deploy/; fi
          if [ -f backend/Procfile ]; then cp backend/Procfile deploy/; fi
          rsync -a backend/dist/ deploy/dist/
          (cd deploy && zip -r ../app.zip .)
          ls -la app.zip

      # ---- Deploy with AWS CLI (no third-party action) ----
      - name: Upload bundle to EB S3 bucket
        id: upload
        run: |
          set -euo pipefail
          BUCKET=$(aws elasticbeanstalk create-storage-location --query S3Bucket --output text)
          echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
          KEY="$EB_APP/${{ github.sha }}.zip"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          aws s3 cp app.zip "s3://$BUCKET/$KEY" --only-show-errors

      - name: Create EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "$EB_APP" \
            --version-label "v-${{ github.sha }}" \
            --source-bundle S3Bucket=${{ steps.upload.outputs.bucket }},S3Key=${{ steps.upload.outputs.key }} \
            --process

      - name: Update EB environment to new version
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "$EB_ENV" \
            --version-label "v-${{ github.sha }}"

      - name: Wait for environment update to finish
        run: |
          aws elasticbeanstalk wait environment-updated \
            --environment-names "$EB_ENV"
